
services:
  php:
    build: ./docker/php
    user: 1000:1000
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "6000:8000"
    networks:
      - blog
    command: "php artisan serve --host 0.0.0.0"

  node:
    image: node:20-alpine
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    networks:
      - blog
    command: "sh -c 'npm install && npm run dev'"

  db:
    image: mysql
    restart: always
    ports:
      - "8083:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Blog
      MYSQL_DATABASE: Blog
      MYSQL_USER: Blog
      MYSQL_PASSWORD: Blog
    volumes:
      - "./docker/db/data:/var/lib/mysql"
    networks:
      - blog

networks:
  blog:
    name: blog
  
